name: sse_request
description: A dart package for consuming SSE (Server Sent Events) using configurable and extensible connection lifecycle and event handling controller
version: 0.2.0
repository: https://github.com/nvkantonio/sse_request
homepage: https://github.com/nvkantonio/sse_request
issue_tracker: https://github.com/nvkantonio/sse_request/issues
topics:
  - sse
  - server-sent-events
  - configurable
  - http-stream

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  meta: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
